# Dockerfile
FROM public.ecr.aws/lambda/python:3.9

RUN yum update -y
RUN yum install -y \
    Xvfb \
    wget \
    gtk3 \
    dbus-glib \
    libpci \
    unzip \
    gcc \
    openssl-devel \
    zlib-devel \
    libffi-devel \
    libgtk-3-0 \
    alsa-lib-devel \
    vim \
    # I think needed for pandas
    libxml2 \
    libxml2-devel \
    g++ \
    yum -y clean all
RUN yum -y groupinstall development

WORKDIR /opt

RUN wget -O- "https://download.mozilla.org/?product=firefox-latest-ssl&os=linux64&lang=en-US" | tar -jx -C /usr/local/

# Borrowed from here: https://github.com/aws-samples/container-web-scraper-example/blob/master/code/Dockerfile
RUN ln -s /usr/local/firefox/firefox /usr/bin/firefox


RUN wget https://github.com/mozilla/geckodriver/releases/download/v0.31.0/geckodriver-v0.31.0-linux64.tar.gz
RUN tar -xf geckodriver-v0.31.0-linux64.tar.gz
RUN ls -lta
RUN rm geckodriver-v0.31.0-linux64.tar.gz

RUN chmod +x geckodriver
RUN export DISPLAY=:99
RUN Xvfb -ac -nolisten inet6 :99 &
# RUN xvfb-run -a firefox --display=:99 --setDefaultBrowser=firefox &

WORKDIR /var/task

# Install selenium
COPY lambda_reqs.txt .
RUN pip3 install -r lambda_reqs.txt

# Copy lambda's main script
COPY app.py .

CMD ["app.lambda_handler"]


# Borrowed from https://dev.to/adelmofilho42/web-scraping-with-python-and-aws-lambda-a-modern-approach-1iok
